# Generated by Django 5.2.9 on 2025-12-30 12:06

import apps.tramite.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tramite.models.procedure_file_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_options', models.JSONField(blank=True, default=list, null=True)),
                ('flow_type', models.CharField(choices=[('NR', 'Normal'), ('CP', 'Copy')], default='NR', max_length=2)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('FINALIZED', 'Finalized'), ('OBSERVED', 'Observed'), ('REJECTED', 'Rejected'), ('SUBSANATION', 'Subsanation'), ('ANNULLED', 'Annulled'), ('PENDING_SCHEDULE', 'Pending by schedule')], default='SENT', max_length=20)),
                ('is_to_finalize', models.BooleanField(default=False)),
                ('is_to_observed', models.BooleanField(default=False)),
                ('is_derive', models.BooleanField(default=False)),
                ('subject', models.TextField(blank=True, null=True)),
                ('subject_derivar', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField()),
                ('registered_out_of_schedule_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado')], unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(editable=False, max_length=3, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('TE', 'Tramite externo'), ('TI', 'Tramite interno'), ('TV', 'Tramite virtual')], default='TI', max_length=10)),
                ('initials', models.CharField(blank=True, max_length=50, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='tramite.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('folios', models.PositiveIntegerField(default=0)),
                ('sender_dni', models.CharField(blank=True, max_length=15, null=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_representante', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_address', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.TextField()),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_annulled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='tramite.agency')),
            ],
        ),
    ]
