# Generated by Django 5.2.9 on 2025-12-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.department')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.province')),
            ],
        ),
    ]
