# Generated by Django 5.2.9 on 2025-12-31 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_department_province_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramite.department'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramite.district'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramite.province'),
        ),
    ]
