# Generated by Django 5.2.9 on 2026-01-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_procedure_department_procedure_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
    ]
