# Generated by Django 5.2.9 on 2026-01-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_procedure_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureflow',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
