# Generated by Django 5.2.9 on 2026-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_procedureflow_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='origin_code',
            field=models.CharField(blank=True, help_text='Código original de la agencia de origen', max_length=20, null=True),
        ),
    ]
