# Generated by Django 5.2.9 on 2026-01-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_procedure_origin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='origin_code',
            new_name='code_destino',
        ),
    ]
