# Generated by Django 5.2.9 on 2026-01-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0008_rename_origin_code_procedure_code_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='start_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
