# Generated by Django 5.2.9 on 2026-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0009_agency_start_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
