# Generated by Django 5.2.9 on 2026-01-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0010_agency_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
