# Generated by Django 5.2.9 on 2026-01-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0011_alter_procedure_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
