# Generated by Django 5.2.9 on 2026-02-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0012_alter_procedure_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureflow',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
