# Generated by Django 5.2.9 on 2026-02-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0013_procedureflow_is_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='due_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
