# Generated by Django 5.2.9 on 2026-02-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0014_procedure_blocked_at_procedure_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('size_mb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('failed', 'Fallido')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='Usuario o CRON', max_length=100, null=True)),
            ],
        ),
    ]
