# Generated by Django 5.2.9 on 2026-02-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0015_globalbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurefile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
