# Generated by Django 5.2.9 on 2026-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0017_systembackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='is_registered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
