# Generated by Django 5.2.9 on 2026-05-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0018_procedure_is_registered_alter_procedure_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureflow',
            name='finalize_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
