# Generated by Django 5.2.9 on 2026-09-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0019_procedureflow_finalize_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='procedure_visibility',
            field=models.CharField(choices=[('ALL', 'Todos los trámites'), ('AGENCY', 'Solo trámites de la agencia'), ('AREA', 'Solo trámites del área')], default='AREA', max_length=20),
        ),
    ]
